name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt install valgrind
        git clone https://github.com/holbertonschool/Betty.git
    - name: install betty
      working-directory: ./Betty
      run: sudo ./Betty/install.sh
    - name: make
      run: make check_style build run_tests check_memory
